name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Corre cada 5 minutos

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep Alive Request
        run: curl -I https://pinky-beauty-bar.onrender.com/ping/
