name: Keep Render Alive

on:
  workflow_dispatch:  # 👈 Esto permite ejecutarlo manualmente
  schedule:
    - cron: '*/5 * * * *'  # Corre cada 5 minutos

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep Alive Request
        run: curl -I https://pinky-beauty-bar.onrender.com/ping/
        
      - name: Keep Zoho-Siigo Sync Alive
        run: curl -I https://zoho-siigo-sync.onrender.com/ping/
